sudo: required
services:
  - docker

before_install:
  - docker build -t maximus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maximus/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-01"
  env: "DockerReact01-env"
  bucket_name: "elasticbeanstalk-us-east-2-636061175964"
  bucket_path: "docker-react-01"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
